# sourced from: https://dev.to/the_one/deploy-to-github-pages-like-a-pro-with-github-actions-4hdg
name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          version: 12.x
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Run deploy script
        run: |
          git config user.name "aidankay1" && git config user.email "34078276+aidankay1@users.noreply.github.com"
          npm run gh-pages-deploy
